### ISSUE TITLE
Handle parametrization in filename

### ISSUE THREAD

**Issue by jakub-borusewicz** [jakub-borusewicz/cue-auto-export#1]
allow parametrization of files using [information injection](https://cuelang.org/docs/concept/using-the-cue-export-command/inputs/#information-injection)

for example:
having hook:

```
repos:
  - repo: https://github.com/jakub-borusewicz/cue-auto-export
    rev: v1.0.2
    hooks:
      - id: cue-auto-export
        exclude: (?x)^(
            cue.mod/.* |
            config/.*
          )$
        args: "--parametrize "{env: local, staging, prod}"
```

you could parametrize

`config-{env}.json.cue`

would generate files

`config-local.json`
`config-staging.json`
`config-prod.json`

generated with variable `env` assigned to proper value using information injection
